apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerwebapp-deployment
  labels:
    app: customerwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerwebapp
  template:
    metadata:
      labels:
        app: customerwebapp
    spec:
      containers:
      - name: customerwebapp
        image: docker.io/lars14/miw-customerwebapp:release0.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
