apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plantr-kafka-volume-claim
  namespace: plantr
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
